// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vault/v1/vault.proto

package vaultv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VaultWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultWriteRequest) Reset() {
	*x = VaultWriteRequest{}
	mi := &file_vault_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultWriteRequest) ProtoMessage() {}

func (x *VaultWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultWriteRequest.ProtoReflect.Descriptor instead.
func (*VaultWriteRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{0}
}

func (x *VaultWriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultWriteRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VaultWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultWriteResponse) Reset() {
	*x = VaultWriteResponse{}
	mi := &file_vault_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultWriteResponse) ProtoMessage() {}

func (x *VaultWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultWriteResponse.ProtoReflect.Descriptor instead.
func (*VaultWriteResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{1}
}

func (x *VaultWriteResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type VaultReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultReadRequest) Reset() {
	*x = VaultReadRequest{}
	mi := &file_vault_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultReadRequest) ProtoMessage() {}

func (x *VaultReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultReadRequest.ProtoReflect.Descriptor instead.
func (*VaultReadRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{2}
}

func (x *VaultReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type VaultReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultReadResponse) Reset() {
	*x = VaultReadResponse{}
	mi := &file_vault_v1_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultReadResponse) ProtoMessage() {}

func (x *VaultReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultReadResponse.ProtoReflect.Descriptor instead.
func (*VaultReadResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{3}
}

func (x *VaultReadResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VaultReadResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetSecretVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretVersionRequest) Reset() {
	*x = GetSecretVersionRequest{}
	mi := &file_vault_v1_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretVersionRequest) ProtoMessage() {}

func (x *GetSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*GetSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{4}
}

func (x *GetSecretVersionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetSecretVersionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListSecretVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretVersionsRequest) Reset() {
	*x = ListSecretVersionsRequest{}
	mi := &file_vault_v1_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretVersionsRequest) ProtoMessage() {}

func (x *ListSecretVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretVersionsRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{5}
}

func (x *ListSecretVersionsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListSecretVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []int32                `protobuf:"varint,1,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretVersionsResponse) Reset() {
	*x = ListSecretVersionsResponse{}
	mi := &file_vault_v1_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretVersionsResponse) ProtoMessage() {}

func (x *ListSecretVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretVersionsResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{6}
}

func (x *ListSecretVersionsResponse) GetVersions() []int32 {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_vault_v1_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{7}
}

func (x *ListSecretsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_vault_v1_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{8}
}

func (x *ListSecretsResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type TestIAMPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIAMPolicyRequest) Reset() {
	*x = TestIAMPolicyRequest{}
	mi := &file_vault_v1_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIAMPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIAMPolicyRequest) ProtoMessage() {}

func (x *TestIAMPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIAMPolicyRequest.ProtoReflect.Descriptor instead.
func (*TestIAMPolicyRequest) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{9}
}

func (x *TestIAMPolicyRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *TestIAMPolicyRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TestIAMPolicyRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type TestIAMPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIAMPolicyResponse) Reset() {
	*x = TestIAMPolicyResponse{}
	mi := &file_vault_v1_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIAMPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIAMPolicyResponse) ProtoMessage() {}

func (x *TestIAMPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_v1_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIAMPolicyResponse.ProtoReflect.Descriptor instead.
func (*TestIAMPolicyResponse) Descriptor() ([]byte, []int) {
	return file_vault_v1_vault_proto_rawDescGZIP(), []int{10}
}

func (x *TestIAMPolicyResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *TestIAMPolicyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_vault_v1_vault_proto protoreflect.FileDescriptor

const file_vault_v1_vault_proto_rawDesc = "" +
	"\n" +
	"\x14vault/v1/vault.proto\x12\bvault.v1\";\n" +
	"\x11VaultWriteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\".\n" +
	"\x12VaultWriteResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\"$\n" +
	"\x10VaultReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"C\n" +
	"\x11VaultReadResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"E\n" +
	"\x17GetSecretVersionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"-\n" +
	"\x19ListSecretVersionsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"8\n" +
	"\x1aListSecretVersionsResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\x05R\bversions\",\n" +
	"\x12ListSecretsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\")\n" +
	"\x13ListSecretsResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"f\n" +
	"\x14TestIAMPolicyRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\"I\n" +
	"\x15TestIAMPolicyResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xf0\x03\n" +
	"\fVaultService\x12G\n" +
	"\n" +
	"VaultWrite\x12\x1b.vault.v1.VaultWriteRequest\x1a\x1c.vault.v1.VaultWriteResponse\x12D\n" +
	"\tVaultRead\x12\x1a.vault.v1.VaultReadRequest\x1a\x1b.vault.v1.VaultReadResponse\x12R\n" +
	"\x10GetSecretVersion\x12!.vault.v1.GetSecretVersionRequest\x1a\x1b.vault.v1.VaultReadResponse\x12_\n" +
	"\x12ListSecretVersions\x12#.vault.v1.ListSecretVersionsRequest\x1a$.vault.v1.ListSecretVersionsResponse\x12J\n" +
	"\vListSecrets\x12\x1c.vault.v1.ListSecretsRequest\x1a\x1d.vault.v1.ListSecretsResponse\x12P\n" +
	"\rTestIAMPolicy\x12\x1e.vault.v1.TestIAMPolicyRequest\x1a\x1f.vault.v1.TestIAMPolicyResponseBbZ`OlympusGCP-Vault/gen/v1/vault;vaultv1b\x06proto3"

var (
	file_vault_v1_vault_proto_rawDescOnce sync.Once
	file_vault_v1_vault_proto_rawDescData []byte
)

func file_vault_v1_vault_proto_rawDescGZIP() []byte {
	file_vault_v1_vault_proto_rawDescOnce.Do(func() {
		file_vault_v1_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_v1_vault_proto_rawDesc), len(file_vault_v1_vault_proto_rawDesc)))
	})
	return file_vault_v1_vault_proto_rawDescData
}

var file_vault_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vault_v1_vault_proto_goTypes = []any{
	(*VaultWriteRequest)(nil),          // 0: vault.v1.VaultWriteRequest
	(*VaultWriteResponse)(nil),         // 1: vault.v1.VaultWriteResponse
	(*VaultReadRequest)(nil),           // 2: vault.v1.VaultReadRequest
	(*VaultReadResponse)(nil),          // 3: vault.v1.VaultReadResponse
	(*GetSecretVersionRequest)(nil),    // 4: vault.v1.GetSecretVersionRequest
	(*ListSecretVersionsRequest)(nil),  // 5: vault.v1.ListSecretVersionsRequest
	(*ListSecretVersionsResponse)(nil), // 6: vault.v1.ListSecretVersionsResponse
	(*ListSecretsRequest)(nil),         // 7: vault.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),        // 8: vault.v1.ListSecretsResponse
	(*TestIAMPolicyRequest)(nil),       // 9: vault.v1.TestIAMPolicyRequest
	(*TestIAMPolicyResponse)(nil),      // 10: vault.v1.TestIAMPolicyResponse
}
var file_vault_v1_vault_proto_depIdxs = []int32{
	0,  // 0: vault.v1.VaultService.VaultWrite:input_type -> vault.v1.VaultWriteRequest
	2,  // 1: vault.v1.VaultService.VaultRead:input_type -> vault.v1.VaultReadRequest
	4,  // 2: vault.v1.VaultService.GetSecretVersion:input_type -> vault.v1.GetSecretVersionRequest
	5,  // 3: vault.v1.VaultService.ListSecretVersions:input_type -> vault.v1.ListSecretVersionsRequest
	7,  // 4: vault.v1.VaultService.ListSecrets:input_type -> vault.v1.ListSecretsRequest
	9,  // 5: vault.v1.VaultService.TestIAMPolicy:input_type -> vault.v1.TestIAMPolicyRequest
	1,  // 6: vault.v1.VaultService.VaultWrite:output_type -> vault.v1.VaultWriteResponse
	3,  // 7: vault.v1.VaultService.VaultRead:output_type -> vault.v1.VaultReadResponse
	3,  // 8: vault.v1.VaultService.GetSecretVersion:output_type -> vault.v1.VaultReadResponse
	6,  // 9: vault.v1.VaultService.ListSecretVersions:output_type -> vault.v1.ListSecretVersionsResponse
	8,  // 10: vault.v1.VaultService.ListSecrets:output_type -> vault.v1.ListSecretsResponse
	10, // 11: vault.v1.VaultService.TestIAMPolicy:output_type -> vault.v1.TestIAMPolicyResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_vault_v1_vault_proto_init() }
func file_vault_v1_vault_proto_init() {
	if File_vault_v1_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_v1_vault_proto_rawDesc), len(file_vault_v1_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_v1_vault_proto_goTypes,
		DependencyIndexes: file_vault_v1_vault_proto_depIdxs,
		MessageInfos:      file_vault_v1_vault_proto_msgTypes,
	}.Build()
	File_vault_v1_vault_proto = out.File
	file_vault_v1_vault_proto_goTypes = nil
	file_vault_v1_vault_proto_depIdxs = nil
}
