// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: vault/v1/vault.proto

package vaultv1connect

import (
	v1 "OlympusGCP-Vault/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/vault/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VaultServiceName is the fully-qualified name of the VaultService service.
	VaultServiceName = "vault.v1.VaultService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VaultServiceVaultWriteProcedure is the fully-qualified name of the VaultService's VaultWrite RPC.
	VaultServiceVaultWriteProcedure = "/vault.v1.VaultService/VaultWrite"
	// VaultServiceVaultReadProcedure is the fully-qualified name of the VaultService's VaultRead RPC.
	VaultServiceVaultReadProcedure = "/vault.v1.VaultService/VaultRead"
	// VaultServiceGetSecretVersionProcedure is the fully-qualified name of the VaultService's
	// GetSecretVersion RPC.
	VaultServiceGetSecretVersionProcedure = "/vault.v1.VaultService/GetSecretVersion"
	// VaultServiceListSecretVersionsProcedure is the fully-qualified name of the VaultService's
	// ListSecretVersions RPC.
	VaultServiceListSecretVersionsProcedure = "/vault.v1.VaultService/ListSecretVersions"
	// VaultServiceListSecretsProcedure is the fully-qualified name of the VaultService's ListSecrets
	// RPC.
	VaultServiceListSecretsProcedure = "/vault.v1.VaultService/ListSecrets"
	// VaultServiceTestIAMPolicyProcedure is the fully-qualified name of the VaultService's
	// TestIAMPolicy RPC.
	VaultServiceTestIAMPolicyProcedure = "/vault.v1.VaultService/TestIAMPolicy"
)

// VaultServiceClient is a client for the vault.v1.VaultService service.
type VaultServiceClient interface {
	VaultWrite(context.Context, *connect.Request[v1.VaultWriteRequest]) (*connect.Response[v1.VaultWriteResponse], error)
	VaultRead(context.Context, *connect.Request[v1.VaultReadRequest]) (*connect.Response[v1.VaultReadResponse], error)
	GetSecretVersion(context.Context, *connect.Request[v1.GetSecretVersionRequest]) (*connect.Response[v1.VaultReadResponse], error)
	ListSecretVersions(context.Context, *connect.Request[v1.ListSecretVersionsRequest]) (*connect.Response[v1.ListSecretVersionsResponse], error)
	ListSecrets(context.Context, *connect.Request[v1.ListSecretsRequest]) (*connect.Response[v1.ListSecretsResponse], error)
	TestIAMPolicy(context.Context, *connect.Request[v1.TestIAMPolicyRequest]) (*connect.Response[v1.TestIAMPolicyResponse], error)
}

// NewVaultServiceClient constructs a client for the vault.v1.VaultService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVaultServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VaultServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	vaultServiceMethods := v1.File_vault_v1_vault_proto.Services().ByName("VaultService").Methods()
	return &vaultServiceClient{
		vaultWrite: connect.NewClient[v1.VaultWriteRequest, v1.VaultWriteResponse](
			httpClient,
			baseURL+VaultServiceVaultWriteProcedure,
			connect.WithSchema(vaultServiceMethods.ByName("VaultWrite")),
			connect.WithClientOptions(opts...),
		),
		vaultRead: connect.NewClient[v1.VaultReadRequest, v1.VaultReadResponse](
			httpClient,
			baseURL+VaultServiceVaultReadProcedure,
			connect.WithSchema(vaultServiceMethods.ByName("VaultRead")),
			connect.WithClientOptions(opts...),
		),
		getSecretVersion: connect.NewClient[v1.GetSecretVersionRequest, v1.VaultReadResponse](
			httpClient,
			baseURL+VaultServiceGetSecretVersionProcedure,
			connect.WithSchema(vaultServiceMethods.ByName("GetSecretVersion")),
			connect.WithClientOptions(opts...),
		),
		listSecretVersions: connect.NewClient[v1.ListSecretVersionsRequest, v1.ListSecretVersionsResponse](
			httpClient,
			baseURL+VaultServiceListSecretVersionsProcedure,
			connect.WithSchema(vaultServiceMethods.ByName("ListSecretVersions")),
			connect.WithClientOptions(opts...),
		),
		listSecrets: connect.NewClient[v1.ListSecretsRequest, v1.ListSecretsResponse](
			httpClient,
			baseURL+VaultServiceListSecretsProcedure,
			connect.WithSchema(vaultServiceMethods.ByName("ListSecrets")),
			connect.WithClientOptions(opts...),
		),
		testIAMPolicy: connect.NewClient[v1.TestIAMPolicyRequest, v1.TestIAMPolicyResponse](
			httpClient,
			baseURL+VaultServiceTestIAMPolicyProcedure,
			connect.WithSchema(vaultServiceMethods.ByName("TestIAMPolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// vaultServiceClient implements VaultServiceClient.
type vaultServiceClient struct {
	vaultWrite         *connect.Client[v1.VaultWriteRequest, v1.VaultWriteResponse]
	vaultRead          *connect.Client[v1.VaultReadRequest, v1.VaultReadResponse]
	getSecretVersion   *connect.Client[v1.GetSecretVersionRequest, v1.VaultReadResponse]
	listSecretVersions *connect.Client[v1.ListSecretVersionsRequest, v1.ListSecretVersionsResponse]
	listSecrets        *connect.Client[v1.ListSecretsRequest, v1.ListSecretsResponse]
	testIAMPolicy      *connect.Client[v1.TestIAMPolicyRequest, v1.TestIAMPolicyResponse]
}

// VaultWrite calls vault.v1.VaultService.VaultWrite.
func (c *vaultServiceClient) VaultWrite(ctx context.Context, req *connect.Request[v1.VaultWriteRequest]) (*connect.Response[v1.VaultWriteResponse], error) {
	return c.vaultWrite.CallUnary(ctx, req)
}

// VaultRead calls vault.v1.VaultService.VaultRead.
func (c *vaultServiceClient) VaultRead(ctx context.Context, req *connect.Request[v1.VaultReadRequest]) (*connect.Response[v1.VaultReadResponse], error) {
	return c.vaultRead.CallUnary(ctx, req)
}

// GetSecretVersion calls vault.v1.VaultService.GetSecretVersion.
func (c *vaultServiceClient) GetSecretVersion(ctx context.Context, req *connect.Request[v1.GetSecretVersionRequest]) (*connect.Response[v1.VaultReadResponse], error) {
	return c.getSecretVersion.CallUnary(ctx, req)
}

// ListSecretVersions calls vault.v1.VaultService.ListSecretVersions.
func (c *vaultServiceClient) ListSecretVersions(ctx context.Context, req *connect.Request[v1.ListSecretVersionsRequest]) (*connect.Response[v1.ListSecretVersionsResponse], error) {
	return c.listSecretVersions.CallUnary(ctx, req)
}

// ListSecrets calls vault.v1.VaultService.ListSecrets.
func (c *vaultServiceClient) ListSecrets(ctx context.Context, req *connect.Request[v1.ListSecretsRequest]) (*connect.Response[v1.ListSecretsResponse], error) {
	return c.listSecrets.CallUnary(ctx, req)
}

// TestIAMPolicy calls vault.v1.VaultService.TestIAMPolicy.
func (c *vaultServiceClient) TestIAMPolicy(ctx context.Context, req *connect.Request[v1.TestIAMPolicyRequest]) (*connect.Response[v1.TestIAMPolicyResponse], error) {
	return c.testIAMPolicy.CallUnary(ctx, req)
}

// VaultServiceHandler is an implementation of the vault.v1.VaultService service.
type VaultServiceHandler interface {
	VaultWrite(context.Context, *connect.Request[v1.VaultWriteRequest]) (*connect.Response[v1.VaultWriteResponse], error)
	VaultRead(context.Context, *connect.Request[v1.VaultReadRequest]) (*connect.Response[v1.VaultReadResponse], error)
	GetSecretVersion(context.Context, *connect.Request[v1.GetSecretVersionRequest]) (*connect.Response[v1.VaultReadResponse], error)
	ListSecretVersions(context.Context, *connect.Request[v1.ListSecretVersionsRequest]) (*connect.Response[v1.ListSecretVersionsResponse], error)
	ListSecrets(context.Context, *connect.Request[v1.ListSecretsRequest]) (*connect.Response[v1.ListSecretsResponse], error)
	TestIAMPolicy(context.Context, *connect.Request[v1.TestIAMPolicyRequest]) (*connect.Response[v1.TestIAMPolicyResponse], error)
}

// NewVaultServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVaultServiceHandler(svc VaultServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	vaultServiceMethods := v1.File_vault_v1_vault_proto.Services().ByName("VaultService").Methods()
	vaultServiceVaultWriteHandler := connect.NewUnaryHandler(
		VaultServiceVaultWriteProcedure,
		svc.VaultWrite,
		connect.WithSchema(vaultServiceMethods.ByName("VaultWrite")),
		connect.WithHandlerOptions(opts...),
	)
	vaultServiceVaultReadHandler := connect.NewUnaryHandler(
		VaultServiceVaultReadProcedure,
		svc.VaultRead,
		connect.WithSchema(vaultServiceMethods.ByName("VaultRead")),
		connect.WithHandlerOptions(opts...),
	)
	vaultServiceGetSecretVersionHandler := connect.NewUnaryHandler(
		VaultServiceGetSecretVersionProcedure,
		svc.GetSecretVersion,
		connect.WithSchema(vaultServiceMethods.ByName("GetSecretVersion")),
		connect.WithHandlerOptions(opts...),
	)
	vaultServiceListSecretVersionsHandler := connect.NewUnaryHandler(
		VaultServiceListSecretVersionsProcedure,
		svc.ListSecretVersions,
		connect.WithSchema(vaultServiceMethods.ByName("ListSecretVersions")),
		connect.WithHandlerOptions(opts...),
	)
	vaultServiceListSecretsHandler := connect.NewUnaryHandler(
		VaultServiceListSecretsProcedure,
		svc.ListSecrets,
		connect.WithSchema(vaultServiceMethods.ByName("ListSecrets")),
		connect.WithHandlerOptions(opts...),
	)
	vaultServiceTestIAMPolicyHandler := connect.NewUnaryHandler(
		VaultServiceTestIAMPolicyProcedure,
		svc.TestIAMPolicy,
		connect.WithSchema(vaultServiceMethods.ByName("TestIAMPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/vault.v1.VaultService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VaultServiceVaultWriteProcedure:
			vaultServiceVaultWriteHandler.ServeHTTP(w, r)
		case VaultServiceVaultReadProcedure:
			vaultServiceVaultReadHandler.ServeHTTP(w, r)
		case VaultServiceGetSecretVersionProcedure:
			vaultServiceGetSecretVersionHandler.ServeHTTP(w, r)
		case VaultServiceListSecretVersionsProcedure:
			vaultServiceListSecretVersionsHandler.ServeHTTP(w, r)
		case VaultServiceListSecretsProcedure:
			vaultServiceListSecretsHandler.ServeHTTP(w, r)
		case VaultServiceTestIAMPolicyProcedure:
			vaultServiceTestIAMPolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVaultServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVaultServiceHandler struct{}

func (UnimplementedVaultServiceHandler) VaultWrite(context.Context, *connect.Request[v1.VaultWriteRequest]) (*connect.Response[v1.VaultWriteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vault.v1.VaultService.VaultWrite is not implemented"))
}

func (UnimplementedVaultServiceHandler) VaultRead(context.Context, *connect.Request[v1.VaultReadRequest]) (*connect.Response[v1.VaultReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vault.v1.VaultService.VaultRead is not implemented"))
}

func (UnimplementedVaultServiceHandler) GetSecretVersion(context.Context, *connect.Request[v1.GetSecretVersionRequest]) (*connect.Response[v1.VaultReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vault.v1.VaultService.GetSecretVersion is not implemented"))
}

func (UnimplementedVaultServiceHandler) ListSecretVersions(context.Context, *connect.Request[v1.ListSecretVersionsRequest]) (*connect.Response[v1.ListSecretVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vault.v1.VaultService.ListSecretVersions is not implemented"))
}

func (UnimplementedVaultServiceHandler) ListSecrets(context.Context, *connect.Request[v1.ListSecretsRequest]) (*connect.Response[v1.ListSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vault.v1.VaultService.ListSecrets is not implemented"))
}

func (UnimplementedVaultServiceHandler) TestIAMPolicy(context.Context, *connect.Request[v1.TestIAMPolicyRequest]) (*connect.Response[v1.TestIAMPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("vault.v1.VaultService.TestIAMPolicy is not implemented"))
}
